[package]
name = "bin"
version = "0.1.0"
edition = "2024"

[dependencies]
# 配置相关依赖
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_json = "1.0"
serde_yaml = "0.9"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"

[[bin]]
name = "sealdb"
path = "src/sealdb.rs"