name: ForceDB Coverage
on: [push, pull_request]
jobs:

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Coverage
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        # Every acount or organization has a unique token
        # export CODECOV_TOKEN='CODECOV_TOKEN=27d0f712-a1c6-42b3-92a5-ad7c9117ed1a'
        make coverage
        #bash <(curl -s https://codecov.io/bash) -f "!mock.go"
        bash <(curl -s https://codecov.io/bash) -f "!mock.go" -t 27d0f712-a1c6-42b3-92a5-ad7c9117ed1a

    # Only private respository need
    - name: Coverage Upload
      uses: codecov/codecov-action@v3
      with:
        token: 27d0f712-a1c6-42b3-92a5-ad7c9117ed1a # not required for public repos
        files: /tmp/forcedb-coverage.out # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
